// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsqshdsfszksxiqveeav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcXNoZHNmc3prc3hpcXZlZWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODg5NzQsImV4cCI6MjA2MjQ2NDk3NH0.-QKQZJxovmLZBhVceY1bGCXDHC1YXBslrcZb6v9K63M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);